### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [JayasreeSuryadevara/Ecletsy#4]
- [x] format it 
\```javascript
{
    entities: {
        users: {
        }
    }
}
\```

- [x] all your data is going to be nested under key of `entities`
- [x] `session` slice of state
- [x] `errors` slice of state
- [x] `ui` slice of state (optional)
- [x] remove password_digest and session_token on a user
- [x] include all the id's of the data in the object
- [x] remove transactions

**Comment by ssoonmi** [comment]
- [x] I think address should be private (users can only see their own address)

**Comment by ssoonmi** [comment]
- [x] products should have a list of reviewIds
- [x] vendors could have a list of productIds

**Comment by ssoonmi** [comment]
Please make the above changes

**Comment by JayasreeSuryadevara** [comment]
Forgot about the associations.. thanks
